#Takes output from tp_calc to calculate the maximum trophic position (food chain length) for each site in dataframe
#
#Args
#fish      A dataframe with d15N data for fish at different sites along a river
#frac      Trophic discrimination factor used to calculate trophic position (default = 3.4)
#
#Output - a dataframe with these columns
#site     Site along river
#species  Fish species (character class)
#id        ID number for individual fish
#maxtp    Trophic position of the fish with the maximum trophic position (FCL)
#
fcl_calc <- function(fish, frac=3.4) {
  
  #call tp_calc
  
  #for(each site in the dataframe generated by tp_calc)
    #find the maximum trophic position (tp) by site
  
  return(as.data.frame(c(site, species, id, maxtp)))
  
}