#Takes output from tp_calc to calculate the maximum trophic position (food chain length) for each site in dataframe
#
#Args
#frac     Trophic discrimination factor used to calculate trophic position (default = 3.4)
#
#Output - a dataframe with these columns
#site     Site along river
#species  Fish species (character class)
#tp       Trophic position
#
fcl_calc <- function(dat, frac) {
  #call tp_calc
  
  #for(each site in the dataframe generated by tp_calc)
    #find the maximum trophic position (tp) by site
}