#' fcl_calc
#'
#' Takes output from tp_calc to calculate the maximum trophic position (food chain length) for each site in dataframe
#
#' @param tp A data frame generated by function tp_calc
#'
#' @return A dataframe of columns sitename and fcl
#'
#' @examples
#' fcl_calc(dat = iris)
#'
fcl_calc <- function(tp) {
  site <- levels(tp$site)
  fcl <- vector(mode = "numeric")
  for(i in site) {
    fcl[i] <- max(tp$tp[dat$site==i])
  }
  fcldf <- data.frame(site, fcl)
  colnames(fcldf) <- c("site", "fcl")
  return(fcldf)
}
