#' tp_calc
#'
#' Takes output from base_sig to calculate the trophic position for each fish (row) in dataframe
#
#' @param base A data frame generated by function base_sig
#' @param fish A data frame with isotope data arranged by species and site
#' @param frac Trophic fractionation factor, default set at 3.4
#'
#' @return A dataframe of columns sitename, d13C, d15N, species, id, and tp
#'
#' @seealso \code{\link{base_sig}}
#' @seealso \code{\link{fcl_calc}}
#' @seealso \code{\link{plot_web}}

base <- base_sig(muss, 3.4)
tp_calc <- function(base, dat, frac=3.4){
  df <- merge(base, dat, by.x = "site", by.y = "site")
  df$tp <- ((((df$d15N-df$baseline))/frac)+1)
  tpdf <- data.frame(df$site, df$d13C, df$d15N, df$species, df$id, df$tp)
  colnames(tpdf) <- c("site", "d13C", "d15N", "species", "id", "tp")
  return(tpdf)
}
