---
title: Supplement for "Effect of hydrogeomorphology on trophic complexity of the Upper Mississippi River (USA)"
author: E. R. Arsenault, J. H. Thorp, M. D. Delong, and R. E. Bowes
date: 03 May 2018
output: pdf_document
fontsize: 12pt
---

<!--Chunk for importing the data-->
```{r import, echo=F}

#Dependencies: csv files "muss.csv" (primary consumer data) and "fish.csv" (fish food web data)

muss <- read.csv("muss.csv", header = T) #primary producer signature data (mussels)
fish <- read.csv("fish.csv", header = T) #fish consumer richness, length, mass, and isotope data

#Output: muss and fish dataframes, data needed for all analyses in this file
```

<!--Chunk for sourcing external scripts (functions)-->
```{r, echo=F}

#Dependencies: external scripts, each with 1 function

source("fish_supp.R")

#Output: function fish_supp to create supplementary table for diversity of fish collected in this study
```

<!--Chunk for creating supplementary tables-->
```{r tables, include=T, echo=F}

#Dependencies: external scripts, muss and fish datasets

musssupp <- fish_supp(muss)
knitr::kable(musssupp, col.names = c("Species", "Count"), caption = "Summary of mussel species collected from 4 sites along the Upper Mississippi River", row.names = F, align = "l")

fishsupp <- fish_supp(fish)
knitr::kable(fishsupp, col.names = c("Species", "Count"), caption = "Summary of fish species collected from 4 sites along the Upper Mississippi River", row.names = F, align = "l")

#Output: supplementary table with fish collection and site information
```
```
